#----------------------------
# Github Action PArt-1 - Basics
#
# Copyleft (c) by Pavel Vasilev 2024

name : My-GithubActions-Basics 

on: 
  push:
    branch:
      - master


jobs:
 my_testing:
   runs-on: ubuntu-latest
   steps:
   - name: Print Hello Message
     run: echo "Hello world from testing"
  



 
    
