#----------------------------
# Github Action PArt-1 - Basics
#
# Copyleft (c) by Pavel Vasilev 2024

name : My-GithubActions-Basics 
env: 
    APPLICATION_NAME    : "MyFlask"
    DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"

    
on: 
  push:
   branches:
      - master


jobs:
 my_testing:
   runs-on: ubuntu-latest
   steps:
   - name: Print Hello Message
     run: echo "Who is the good girl?"
   - name: Execute few commands
     run : |
       echo "Hello Message1"
       echo "Hello Message2"
 my_deploy:
   runs-on: ubuntu-latest
   needs: [my_testing]

   steps:
   - name: Print Hello Message in Deploy
     run: echo "YOU ARE THE GOOD GIRL"     
