#----------------------------
# Github Action PArt-1 - Basics
#
# Copyleft (c) by Pavel Vasilev 2024

name : My-GithubActions-Basics 

on: 
  push:
    branch:
      - master


jobs:
 my_testing:
   runs-on: ubuntu-latest
   steps:
   - name: Print Hello Message
     run: echo "Who is the good girl?"
 my_deploy:
   runs-on: ubuntu-latest
   needs: [mymy_testing]

   steps:
   - name: Print Hello Message in Deploy
   run: echo "YOU ARE THE GOOD GIRL"     
